### ISSUE TITLE
Speeding up DNS requests

### ISSUE THREAD

**Issue by drocsid** [socketry/rubydns#70]
Hi,

I needed a simple local DNS server to help me resolve internal names like ip-238.32.42.14.*.internal locally to the implied IP address. RubyDNS worked well for this and have a simple script working and resolving the names as expected. I've configured a RubyDNS server as the first entry via network manager / resolv.conf in linux.

However my DNS requests are resolving significantly more slowly when requesting a regular record. I'm no DNS expert but assume that generally on a host some caching mechanism is employed and that's why I'm so much slower when running the script.

Is the caching assumption correct regarding the slowdown? If so should I just use a map and some sort of timer to expire the records in that map? Can you give me other advice regarding my resolver or DNS configuration?

Thanks again for providing this DNS solution!

```
require 'rubydns'

  INTERFACES = [
      [:udp, "0.0.0.0", 53],
      [:tcp, "0.0.0.0", 53],
  ]

  IN = Resolv::DNS::Resource::IN

# Use upstream DNS for name resolution.

  def getResolver(ipaddress,port)
    return RubyDNS::Resolver.new([[:udp,ipaddress,port],[:tcp,ipaddress,port]])
  end
  
  #GOOGLE_DNS = RubyDNS::Resolver.new([[:udp, "8.8.8.8", 53], [:tcp, "8.8.8.8", 53]])
  # TODO: get these from resolv.conf or network manager
  NET_1 = getResolver("101.123.128.20",53)
  #NET_2 = getResolver("101.124.82.144",53)


# Start the RubyDNS server
  RubyDNS::run_server(INTERFACES) do
    single_ip_match_group = /ip-([^.]*).*/ #internal/
    match(single_ip_match_group) do |transaction, match_data|
      logger.info("matched ")
      logger.info(match_data[1].to_s)
      ip = match_data[1].to_s.gsub("-",".")
      transaction.respond!(ip)
    end

    # Default DNS handler
    otherwise do |transaction|
      logger.info("not matched")
      transaction.passthrough!(NET_1)
    end
  end

```

**Comment by ioquatix** [comment]
Thanks for your detailed report. I will take a look at it, at my earliest convenience.

**Comment by ioquatix** [comment]
In the first instance, can you try using `dig` to go directly to the upstream server and then via your RubyDNS server and report back the latency?

**Comment by drocsid** [comment]
Hi @ioquatix ,

I didn't mention before I'm not sure that it's DNS resolution that is causing my issues. What I've noticed is when I use the rubydns resolver script and try to visit a website it's very slow to load vs. without; using either `firefox` or `chrome` . Then I assumed this was related to DNS resolution, but you might know better than me.

*Regarding your questions* 

While running the rubydns script with a slightly different DNS server IP:

```dig slashdot.org

; <<>> DiG 9.10.3-P4-Debian <<>> slashdot.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42406
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;slashdot.org.			IN	A

;; ANSWER SECTION:
slashdot.org.		44	IN	A	216.105.38.15

;; Query time: 93 msec
;; SERVER: 10.12.138.20#53(10.12.138.20)
;; WHEN: Thu Feb 22 16:51:12 PST 2018
;; MSG SIZE  rcvd: 57
```

Without running RubyDNS script:

```
dig slashdot.org

; <<>> DiG 9.10.3-P4-Debian <<>> slashdot.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13114
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;slashdot.org.			IN	A

;; ANSWER SECTION:
slashdot.org.		300	IN	A	216.105.38.15

;; Query time: 25 msec
;; SERVER: 10.12.138.20#53(10.12.138.20)
;; WHEN: Thu Feb 22 16:52:27 PST 2018
;; MSG SIZE  rcvd: 57
```

**Comment by drocsid** [comment]
Not sure if I made this clear or not, but I'm setting this ruby resolver as my first entry (127.0.0.1) via network-manager to resolv.conf. (ignoring dhcp assigned 10.12.138.20 as the first entry to resolv.conf)

@ioquatix Could it be that the resolver 10.12.138.20 above doesn't resolve all my requests, is timing out; so I'm cycling through my other resolvers from resolv.conf, and that's causing the delay?

However, I would think this would not be the case because 10.12.138.20 is normally my first resolver assigned by dhcp / network-manager when I don't override (as mentioned above), and I would then expect the same timeout when not using the script.

Maybe I should try logging the passthrough?

**Comment by drocsid** [comment]
@ioquatix Any ideas regarding this?

**Comment by ioquatix** [comment]
My kids have been sick this week, so I haven't had much spare time, but rest assured I appreciate your continued interest in this performance problem and I certainly want to look into it.

**Comment by matti** [comment]
@drocsid did you put `localhost` or `127.0.0.1` as dns server?

running `examples/basic-dns.rb`

query takes 1s:
```
$ time dig @localhost -p 5300 example.com
..
;; Query time: 23 msec
dig @localhost -p 5300 example.com  0.00s user 0.01s system 0% cpu 1.037 total
```

query takes 0.03s:
```
$ time dig @127.0.0.1 -p 5300 example.com
..
;; Query time: 23 msec
dig @127.0.0.1 -p 5300 example.com  0.00s user 0.01s system 25% cpu 0.031 total
```

**Comment by ioquatix** [comment]
Judging by

```
;; Query time: 25 msec
```

in the sample output from @drocsid I'm going to assume your assessment is correct @Matti - thanks for adding to the discussion. I believe this is now resolved!

**Comment by matti** [comment]
I think this has something to do with ipv6?

**Comment by ioquatix** [comment]
What makes you say that?

**Comment by matti** [comment]
I have a vague memory that using "localhost" instead of 127.0.0.1 starts some ipv6 madness - I think that's whats going on here: first resolves are done with ipv6 that times out in 1s and then ipv4 is fast as expected
