### ISSUE TITLE
description in gemspec file seems to be old

### ISSUE THREAD

**Issue by takahashim** [socketry/rubydns#71]
[spec.description in rubydns.gemspec](https://github.com/socketry/rubydns/blob/f20a2fca73c587a492938c3a1d0f4d0746537f5a/rubydns.gemspec#L18) says:

```
In addition, RubyDNS includes a high-performance asynchronous DNS resolver
built on top of Celluloid. 
```

It should be `build on top of async-dns` or `async-io`, right?

**Comment by ioquatix** [comment]
Yes that's right. Thanks for pointing that out. This gem is almost 10 years old and has undergone several major changes, including `EventMachine`, `Celluloid::IO`, and now `Async`.
